chore: implement devpkg module resolver (#2153)
Co-authored-by: iGroza <xneonxneon1@gmail.com>

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,3 +1,9 @@
+# if devpkg is enabled, throw error and exit with code 1
+if [ -f .devpkg.json ] && [ "$(jq -r '.enabled' .devpkg.json)" = "true" ]; then
+  echo "\033[31mError: DevPkg is enabled. Please disable .devpkg.json to proceed with commit.\033[0m" >&2
+  exit 1
+fi
+
 #!/bin/sh
 npx patch-package --error-on-fail
 
